In [3]:
import numpy as np                     # 배열(ndarray) 데이터를 다루는 클래스 / 행렬(matrix)연산에 특화된 패키지
import pandas as pd                    # 데이터프레임이라는 데이터 관리에 자주 쓰이는 클래스 패키지

sample_list=[1,2,3,4,5]                # List 생성
sample_list

[1, 2, 3, 4, 5]

In [4]:
sample_array=np.array([1,2,3,4,5])     # List를 사용하여 배열을 생성
sample_array

array([1, 2, 3, 4, 5])

In [5]:
sample_array + 2                       # 배열을 대상으로 하는 연산은 배열 내부 데이터 모두에 적용된다

array([3, 4, 5, 6, 7])

In [6]:
sample_array * 2

array([ 2,  4,  6,  8, 10])

In [7]:
np.array([1,2,"A"])                    # 만약 숫자와 문자열을 동시에 배열에 넣으려 한다면 모두 문자열로 취급?

array(['1', '2', 'A'], dtype='<U21')

In [8]:
sample_array_2 = np.array(             # 2차원 배열도 생성이 가능하다. 
 [[1,2,3,4,5],                         # (2-dimensional array)
  [6,7,8,9,10]])
sample_array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

![대체 텍스트](https://user-images.githubusercontent.com/56021593/77227291-91abbc00-6bc2-11ea-924d-77614946ff12.png)

In [9]:
sample_array_2.shape                  # .shape로 행(row)수와 열(column)수 확인

(2, 5)

# 등차수열 (Arithmetic progression)

\begin{align}
a_n= a_1 + (n -1)d
\end{align}

a_n =	the nᵗʰ term in the sequence<br>
a_1 = the first term in the sequence<br>
d= the common difference between terms
<br><br>

등차수열이란 {1,2,3,4,5}와 같이 앞뒤 값의 차이가 동일한 수열이다. 아래의 예시의 경우 각 값간의 차이가 1인 등차수열이다. <br>
<br>
인수의 시작위치는 start, 종료위치는 stop, 차잇값은 step<br><br>
**stop**으로 지정한 값은 배열에 포함되지 않는다.<br><br>
1부터 5까지 숫자를 넣을 것이기 때문에 stop에는 5에 1을 더한 6을 지정

In [10]:
np.arange(start = 1, stop = 6, step = 1)    # 시작이 1이고, 차이가 1인 등차수열 {1,2,3,4,5}

array([1, 2, 3, 4, 5])

In [11]:
np.arange(start = 0.1, stop = 1.0, step = 0.2) 

array([0.1, 0.3, 0.5, 0.7, 0.9])

In [12]:
np.tile("A", 5)  #같은 값을 잔뜩 채운 배열은 np.tile 함수 사용, "A" 5개

array(['A', 'A', 'A', 'A', 'A'], dtype='<U1')

In [13]:
np.tile("0",4)

array(['0', '0', '0', '0'], dtype='<U1')

In [14]:
np.zeros(4)   # 모두 0인 배열을 만드는 함수

array([0., 0., 0., 0.])

In [15]:
np.zeros([2,3])  # 2차원으로 배열로도 생성 가능. 인자로 '행(row)수, 열(column)수 순의 값이 있는 list

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
sample_df = pd.DataFrame({         #데이터프레임 생성
  'col1' : sample_array,
  'col2' : sample_array*2,
  'col3' : ["A","B","C","D","ㄱ"] 
})
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    ㄱ


In [17]:
sample_df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    ㄱ

In [19]:
from google.colab import files
uploaded = files.upload()

Saving 2-4-1-sample_data.csv to 2-4-1-sample_data.csv


In [20]:
file_data = pd.read_csv("2-4-1-sample_data.csv")   #CSV파일 읽어오기
# print(file_data)

file_data                                          #CSV파일 내부 정보 시각화

col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C

In [21]:
df_1 = pd.DataFrame({                  #기존의 데이터프레임을 병합하여 새로운 데이터프레임 생성
   'col1' : np.array([1,2,3]),
   'col2' : np.array(["A","B","C"])    
})

df_2 = pd.DataFrame({
    'col1' : np.array([4,5,6]),
    'col2' : np.array(["D","E","F"])    
})

pd.concat([df_1, df_2])

col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [29]:
pd.concat([df_1, df_2], axis=1)     # axis=1이란 인자 추가하면 3행 4열 데이터프레임 생성
                                    # pd.concat함수는 병합하는데 쓰임/ DB조작에서도 사용(SQL)
                                    # pandas 데이터프레임과 SQL 비슷한 점이 있음

col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

In [22]:
print(sample_df)

   col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    ㄱ


In [23]:
print(sample_df.col2)     #열이름 지정해서 호출하려면 (.)사용

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64


In [24]:
print(sample_df["col2"]) #대괄호를 이용해서 추출

0     2
1     4
2     6
3     8
4    10
Name: col2, dtype: int64


In [25]:
print(sample_df[["col2","col3"]]) # 리스트형식으로도 복수형식 추출가능

   col2 col3
0     2    A
1     4    B
2     6    C
3     8    D
4    10    ㄱ


In [27]:
print(sample_df.drop("col3", axis = 1)) # 지정한 열만 빼고 데이터 추출도 가능

   col1  col2
0     1     2
1     2     4
2     3     6
3     4     8
4     5    10


In [28]:
sample_df.head(n = 3) # 처음행 3개만 가져오기(.head함수)

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C

In [29]:
sample_df.query('index==0')   # query함수로 최초 1행(row) 호출

col1  col2 col3
0     1     2    A

In [31]:
sample_df.query('col3 == "A"') # col3열에서 값이 A인 행만 찾는 법

col1  col2 col3
0     1     2    A

In [32]:
sample_df.query('col3=="A" | col3=="D" ') # 복수 조건 지정(col 3의 값이 A 또는 D인 조건에 맞는 행 출력/OR 조건)

col1  col2 col3
0     1     2    A
3     4     8    D

In [35]:
sample_df.query('col3=="A" & col1== 3 ') # 복수 조건 지정(col 3의 값이 "A" 그리고 col1 값이 "3"인 조건에 맞는 행 출력/AND 조건)
                                         # 조건에 맞는 데이터가 없다

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [36]:
sample_df.query('col3=="A"') [["col2","col3"]] # 행(row) 열(column)에 모두 지정

col2 col3
0     2    A